---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: access-os-gnome
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - update-dconf.sh

  - type: rpm-ostree
    repos:
    install:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - steam
      - steam-devices
      - google-chrome-stable
      - git
      - gh
      - fastfetch
      - gedit
      - lxterminal
      - caja
      - npm
      - rpi-imager
      - python3-psutil
      - aria2
      - breeze-gtk
      - ocean-sound-theme
      - gnome-tweaks
      - quickemu
      - virt-manager
      - dconf-editor
      - stack
      - haskell-platform
      - fluidsynth
      - vlc
      - yt-dlp
      - mpv
      - mplayer
      - sox
      - wine
      - winetricks
      - wine-mono
      - android-tools
      - rust
      - cargo
      - tailscale
      - wget
      - ntfs-3g
      - rustfmt
      - cargo-clippy
      - samba
      - samba-client
      - samba-common
      - copr-cli
      - rpmdevtools
      - rpmlint
      - thunderbird
      - arch-install-scripts
      - micro
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
